# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - triggers: [":date", ":today"]
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d %m %Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/


  # MY Matches
  # ZERO for now

  # Important symbols! (most on Cyrillic)
  - trigger: "‚Ññ"
    replace: "#"
  - trigger: "--"
    replace: "‚Äî"
  - trigger: ":–≥—Ä–Ω"
    replace: "‚Ç¥"
  - triggers: [" º º", "\"+"]
    replace: "@"

  # Emojis (most of for Obsidian)
  - triggers: [":100", "100+"]
    replace: "üíØ"
  - triggers: [":^", "—Ä—à–ø+", "—Ä+"]
    replace: "üî∫" # Obsidian
  - triggers: ["—Ä—Ä—Ä", hhh"]
    replace: "‚è´"
  - triggers: ["—å—å—å", "mmm"]
    replace: "üîº"
  - triggers: ["lll", "–¥–¥–¥"]
    replace: "üîΩ"
  - trigger: "–¥+"
    replace: "‚è¨"
  - triggers: ["dat+", "data+"]
    replace: "dataview"

  # Obsidian
  - triggers: ["[[l", "[[–ª", "[[–¥"]
    replace: " | [[fname|alt]]"
  # - triggers: ["¬ª¬ª", ")_", ")+"] # isn't work first((
  #   replace: ">"  # Don't needed anymore, [Alt + 7] combination are better, dont know before about))
  - triggers: ["–π¬ª", "–π–Æ", "q>", "–π—é", "–ô–Æ"]
    replace: "> [!$|$]"
  - triggers: ["-t", "-–µ"]
    replace: "- [ ]"
    word: true
  - triggers: ["log+", "–±–∞–Ω–∫–∞+"]
    replace: "log::üíå"

  # App NAMES
  - triggers: ["gh", "GH", "–≥—Ö", "–ì–•", "–ø—Ä+", "–ø—Ä="]
    replace: "GitHub"
    word: true
  - trigger: "–º—ñ—Å—â–≤—É"
    replace: "VS Code"
  - trigger: "–ø—à–µ"
    replace: "git"
  - triggers: ["–¥–æ–∫–µ—Ä", "–î–æ–∫–µ—Ä", "–≤—â—Å–ª—É–∫"]
    replace: "Docker"

  - triggers: ["–ë–ª—É", "–±–ª—É", "–∏–¥–≥+", "Bly+", "blu+"]
    replace: "Bluesky"
  - triggers: ["–Æ–¢", "—é—Ç", "yy", "—é—é", "YT+", "yt+", "–Æ—Ç—É–±+"]
    replace: "YouTube"
    word: true
  - triggers: ["–Æ–ú", "—é–º"]
    replace: "YT Music"
    word: true
  - triggers: ["DD", "–¥—ñ—Å–∫–æ—Ä"]
    replace: "Discord"
  - triggers: ["—Ä–µ–¥–¥—ñ—Ç", "reddit", "–∫—É–≤–≤—à–µ", "–∫—É–≤+", "–†–µ–¥–¥—ñ—Ç"]
    replace: "Reddit"
  - triggers: ["ins=", "—à—Ç—ñ=", "—ñ–Ω—Å—Ç–∞", "Ins+"]
    replace: "Instagram"
    word: true
  - triggers: ["in+", "linkedin", "—à—Ç+", "–¥—à—Ç+", "–¥—à—Ç–ª—É–≤—à—Ç", "lin+"]
    replace: "LinkedIn"

  - triggers: ["–¢–ì", "—Ç–≥", "tg", "–µ–ø+"]
    replace: "TG"
  - triggers: ["–ø–∑–µ", "gpt"]
    replace: "GPT"
  - triggers: ["Tel=", "tel=", "–µ—É–¥—É–ø–∫—Ñ—å", "–µ—É–¥="]
    replace: "Telegram"
  - triggers: ["—Å–ø–∑–µ", "cgpt"]
    replace: "Chat GPT"
  - triggers: ["obs+", "obsid", "–æ–±—Å+", "—â–∏—ñ+", "–û–±—Å—ñ–¥—ñ–∞–Ω", "–æ–±—Å—ñ–¥—ñ–∞–Ω"]
    replace: "Obsidian"
  - triggers: ["espanso", "—É—ñ–∑—Ñ—Ç—ñ—â", "—É—ñ–∑+"]
    replace: "Espanso"
  - triggers: ["cq+", "—Å–π+", "—Å—â–∑–Ω–π"]
    replace: "CopyQ"
  - triggers: ["—Å–¥—Ñ–≥–≤—à", "claudie", "Claudie", "cl="]
    replace: "Claude"
  - triggers: ["Hil+", "—Ä—à–¥+", "—Ä—à–¥—â–ª—Ñ–¥"]
    replace: "Hilocal"

  - triggers: ["—Ñ—Ç–≤–∫—â", "andro", "—Ñ—Ç–≤+"]
    replace: "Android"
  - triggers: ["—ñ—Ñ—å+", "sam+", "Sam+"]
    replace: "Samsung"
  - triggers: ["bit+", "–∏—à–µ+"]
    replace: "Bitwarden"
  - triggers: ["–ª—ñ–Ω—É–∫—Å", "–õ—ñ–Ω—É–∫—Å", "linux"]
    replace: "Linux"

  # Espanso
  - triggers: ["w:t", "—Ü+", "—Ü:", "wt+"]
    replace: "word: true"
  - triggers: ["es2", "—É—ñ2"]
    replace: "- triggers: [\"\", \"\"]
      replace: \"$|$\""

  # –î–æ–ø–∏—Å—É–≤–∞–Ω–Ω—è/–ø—Ä–æ–ø–æ–∑–∏—Ü—ñ—ó —Å–ª–æ–≤–∞ (–∑–∞–∫—ñ–Ω—á–µ–Ω–Ω—è)
#  - trigger: "–∫–æ—Ä–∏—Å—Ç"
#    replace: "–∫–æ—Ä–∏—Å—Ç—É—î—Ç—å—Å—è"
#  - trigger: "–∫–æ—Ä–∏—Å—Ç"
#    replace: "–∫–æ—Ä–∏—Å—Ç—É—î—Ç–µ—Å—è"
#  - trigger: "–∫–æ—Ä–∏—Å—Ç"
#    replace: "–∫–æ—Ä–∏—Å—Ç—É—é—Å—è" # –¥–æ–æ–ø—Ä–∞—Ü—é–≤–∞—Ç–∏ —Ü—ñ –ö–æ—Ä–∏—Å—Ç —Ç—Ä–µ–±–∞!!))
#  - trigger: "–∫–æ—Ä–∏—Å—Ç"     # –±–æ –∫—Ä—ñ–º —Ç–æ–≥–æ —â–æ –Ω–µ –≤—Å—ñ –∑–∞–∫—ñ–Ω—á–µ–Ω–Ω—è —î,
                            # —Ç–æ —â–µ –±–∞–≥–∏ –ø—Ä–æ–≥–∞ –º–∞—î –Ω–∞ —Ü—ñ —Å–ª–æ–≤–∞ —á–æ–º—É—Å—å..
                            # —Ç–æ–º—É –ø–æ–∫–∏ –≤—ñ–¥–∫–ª—é—á–∏–≤ —Ü—ñ —Å–ª–æ–≤–∞
#    replace: "–∫–æ—Ä–∏—Å—Ç–æ–≤—É–≤–∞—Ç–∏"
#  - trigger: "–∫–æ—Ä–∏—Å—Ç"
#    replace: "–∫–æ—Ä–∏—Å—Ç—É–≤–∞—Ç–∏—Å—è"
#  - trigger: "–∫–æ—Ä–∏—Å—Ç"
#    replace: "–∫–æ—Ä–∏—Å—Ç–∞–Ω–Ω—è"
#  - trigger: "–∫–æ—Ä–∏—Å—Ç"
#    replace: "–∫–æ—Ä–∏—Å—Ç–æ–≤—É–≤–∞–≤"
#  - trigger: "–∫–æ—Ä–∏—Å—Ç"
#    replace: "–∫–æ—Ä–∏—Å—Ç–æ–≤—É—é—Ç—å"

  - trigger: "–æ—Ñ"
    replace: "–æ—Ñ—ñ—Ü—ñ–π–Ω—ñ"
    word: true

  - trigger: "–∞–Ω–≥+"
    replace: "–∞–Ω–≥–ª–æ–º–æ–≤–Ω—É"
  - trigger: "–ê–Ω–≥+"
    replace: "–ê–Ω–≥–ª—ñ–π—Å—å–∫—É"
  - trigger: "—É–∫—Ä+"
    replace: "—É–∫—Ä–∞—ó–Ω—Å—å–∫–∞"
  - trigger: "—É–∫—Ä+"
    replace: "—É–∫—Ä–∞—ó–Ω—Å—å–∫—É"
  - trigger: "—É–∫—Ä+"
    replace: "—É–∫—Ä–∞—ó–Ω—Å—å–∫—ñ–π"
  - trigger: "—É—Ç–ø"
    replace: "ENG"

  - trigger: "–∫–æ–Ω+"
    replace: "–∫–æ–Ω—Ñ—ñ–≥—É—Ä–∞—Ü—ñ—é"
  - triggers: ["–∫–æ–Ω—Ü+", "–∫–æ–Ω+"]
    replace: "–∫–æ–Ω—Ü–µ–Ω—Ç—Ä–∞—Ü—ñ—ó (–±–µ–∑ —Å–ø–æ–≤—ñ—â–µ–Ω—å)"
  - trigger: "—Ä–µ–∞+"
    replace: "—Ä–µ–∞–ª—ñ–∑–æ–≤–∞–Ω–æ"
  - trigger: "—Å–º–∞—Ä—Ç+"
    replace: "—Å–º–∞—Ä—Ç—Ñ–æ–Ω"
  - trigger: "–∞–ª—å—Ç+"
    replace: "–∞–ª—å—Ç–µ—Ä–Ω–∞—Ç–∏–≤–Ω—ñ"

  # –í–∏–ø—Ä–∞–≤–ª–µ–Ω–Ω—è —Å–ª—ñ–≤ —Ç–∞ –ø–æ–º–∏–ª–æ–∫
  - triggers: ["–ì—É–≥–ª—é", "–≥—É–≥–ª—é"]
    replace: "“ê—É“ë–ª—é"
    word: true
  - triggers: ["–ì—É–≥–ª", "–≥—É–≥–ª"]
    replace: "“ê—É“ë–ª"
    word: true
  - trigger: "–∞—É–¥—ñ–æ—á–∞—Ç–∏"
    replace: "–∞—É–¥—ñ–æ-—á–∞—Ç–∏"

  # –°—É—Ä–∂–∏–∫-‚Äî –≤–∏–ø—Ä–∞–≤–ª–µ–Ω–Ω—è
  - trigger: "–∑–∞–≥—Ä—É–∂–µ–Ω–∏–π"
    replace: "–∑–∞–≤–∞–Ω—Ç–∞–∂–µ–Ω–∏–π"

  # –ê–Ω–≥ —Ç—Ä–∞–Ω—Å–ª—ñ—Ç/–≤—ñ–¥–ø–æ–≤—ñ–¥–Ω–∏–∫–∏
  - trigger: "—Ä—ñ–¥–º—ñ"
    replace: "Readme"
  - triggers: ["Markd", "–º–∞—Ä–∫–¥", "md+"]
    replace: "Markdown"
  - triggers: ["–≤–µ–±+", "–í–ï–ë+", "—Ü—É–∏"]
    replace: "WEB"
  - triggers: ["–ê–ü–Ü+", "—Ñ–∑—à", "–∞–ø—ñ+"]
    replace: "API"
  - triggers: ["–∫–æ–Ω—Ñ—ñ–≥"]
    replace: "config"
  - triggers: ["fos+", "foss+", "os+"]
    replace: "Open Source"
  - triggers: ["–∞–∫—É—É", "—Ñ—Ä—ñ+"]
    replace: "free"
  - triggers: ["—Ç—Ä—ñ–∞–ª", "–µ–∫—à—Ñ–¥"]
    replace: "trial"
  - triggers: ["—Ñ–∑–∑", "–∞–ø–∫–∞", "–∞–ø–∫—É"]
    replace: "app"
  - triggers: ["–ë–ª—é—Ç—É–∑", "–±–ª—é—Ç—É–∑", "–±–ª—é+", "–∏–¥–≥+"]
    replace: "Bluetooth"

  # –ü–µ–≤–Ω—ñ –≤–ª–∞—Å–Ω—ñ –Ω–∞–∑–≤–∏ (some main)
  - triggers: ["namir+", "—Ç—Ñ—å—à–∫"]
    replace: "namirGO"
  - triggers: ["iphone", "—à–∑—Ä—â—Ç—É", "—à–∑—Ä+", "iph+"]
    replace: "iPhone"
  - triggers: ["mac+", "mackbook", "—å—Ñ—Å+"]
    replace: "MackBook"

  # –ú–æ—ó —Å–Ω—ñ–ø–ø–µ—Ç–∏ (–ü—É–±–ª—ñ—á–Ω—ñ —Ç—ñ–ª—å–∫–∏)
  - triggers: ["—à–µ–º+", "itv+"]
    replace: "[–ë—ñ–ª—å—à–µ –≤—ñ–¥—ñ–±—Ä–∞–Ω–∏—Ö –Ü–¢ –≤–∞–∫–∞–Ω—Å—ñ–π —Ç—É—Ç](https://t.me/+ampaIMJKmu8yODAy)"
  - triggers: ["–ø–≥—Ñ+", "gua+"] # for GPT and others AI
    replace: "–î–∞–π –≤—ñ–¥–ø–æ–≤—ñ–¥—å —Ç—ñ–ª—å–∫–∏ —É–∫—Ä–∞—ó–Ω—Å—å–∫–æ—é –º–æ–≤–æ—é!"
  - triggers: ["–∞–∫—â—Ç–µ—É—Ç–≤+", "–∞—É+", "fe+"]
    replace: "Front-end DEV"
  - triggers: ["bio+", "–∏—à—â+"]
    replace: "https://putsan.bio.link"

  # –°–ª–µ–Ω–≥ —Ç–∞ –°–∫–æ—Ä–æ—á–µ–Ω–Ω—è —É–∫—Ä –ø–µ—Ä–µ–≤–∞–∂–Ω–æ
  - trigger: "—é–∑–∞–≤+"
    replace: "–≤–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É–≤–∞–≤"
  - trigger: "—é–∑–∞—é—Ç—å"
    replace: "–≤–∏–∫–æ—Ä–∏—Å—Ç–æ–≤—É—é—Ç—å"
  - trigger: "–º–∞–≥–∞–∑"
    replace: "–º–∞–≥–∞–∑–∏–Ω"
    word: true
  # –ê–±—Ä–µ–≤—ñ–∞—Ç—É—Ä–∏
  - triggers: ["seo", "—ñ—É—â", "–Ü–£–©"]
    replace: "SEO"
  - triggers: ["foss+", "–∞—â—ñ—ñ", "–ê–©–Ü–Ü"]
    replace: "FOSS"
  - triggers: ["–º–∑—Ç", "vpn"]
    replace: "VPN"
  - triggers: ["usb", "–≥—ñ–∏", "–ì–Ü–ò"]
    replace: "USB"
